#!/bin/sh

export HOME=/var/lib/nagios
export PATH=/usr/sbin:$PATH

case "$1" in
    up)         #command[check_riak_up]=/usr/lib/riak/erts-5.8.4/bin/escript /usr/lib/riak_nagios/check_riak_up.escript 
        /usr/lib/riak/erts-5.8.4/bin/escript /usr/lib/riak_nagios/check_riak_$1.escript 
    	;;
    end_to_end) #command[check_riak_end_to_end]=/usr/lib/riak/erts-5.8.4/bin/escript /usr/lib/riak_nagios/check_riak_end_to_end.escript s2p406.san2 8198 riak 
        /usr/lib/riak/erts-5.8.4/bin/escript /usr/lib/riak_nagios/check_riak_$1.escript $2 $3 $4
        ;;
    repl)       #command[check_riak_repl_to_dfw1]=/usr/lib/riak/erts-5.8.4/bin/escript /usr/lib/riak_nagios/check_riak_repl.escript server san-diego-on-webb-chapel
#command[check_riak_repl_from_dfw1]=/usr/lib/riak/erts-5.8.4/bin/escript /usr/lib/riak_nagios/check_riak_repl.escript client webb-chapel-on-san-diego
	/usr/lib/riak/erts-5.8.4/bin/escript /usr/lib/riak_nagios/check_riak_$1.escript $2 $3
        ;;
    admin)
        /usr/lib/riak/erts-5.8.4/bin/escript /usr/lib/riak_nagios/check_riak_$1.escript $2 $3 $4
        ;;
    *)
        echo "Usage:" 
        ;;
esac